services:
  - type: web
    name: tts-translator
    env: docker
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService: tts-translator-db
        property: host
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: tts_translator
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        generateValue: true

databases:
  - name: tts-translator-db
    plan: free
    region: oregon
